### PR TITLE
BZ #1833035 - Implement bulk ack

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by adamruzicka** [comment]
@j00bar could you please take a look?

**Comment by j00bar** [comment]
Looks cool to me. I don't understand this part of the code though:

https://github.com/project-receptor/receptor-satellite/pull/1/files#diff-5ce0c77eb223d1b2077758a7485e5888R25-R34

**Comment by adamruzicka** [comment]
It is not really elegant and it is there only conform to the spec (see the extract for this PR https://github.com/project-receptor/receptor-satellite/issues/2).

**Comment by adamruzicka** [comment]
I take it there are no more comments to this so I'll go ahead and merge this

**Pull request merged**
